spring:
  application:
    name: api-sousadev-acompanhamento
  datasource:
    url: jdbc:mysql://localhost:3306/essentials
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
    port: 8080